# -*- coding: utf-8 -*-
"""Prediksi.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ3DfwmeaN89xho7gd-IYlmi2NoQbkgq
"""

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

from joblib import load

# Muat model yang sudah disimpan
model = load('/content/random_forest_model.joblib')

scaler = load('scaler (2).pkl')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data_prediksi = pd.read_csv('data_cleaned (1).csv')
data_prediksi

#Misal Yang Ingin Di Prediksi Adalah
#1. Data Urutan Ke 5 Dengan Target Attrition 1 (Yes)
#2. Data Urutan Ke 1055 Dengan Target Attrition 0 (No)

# Ambil baris ke-5
data_prediksi1 = data_prediksi.iloc[[4]]
data_prediksi1

# Pisahkan fitur (X) dan target (Y)
X = data_prediksi1.drop(columns='Attrition')
y = data_prediksi1['Attrition']

# Standardisasi dengan scaler yang telah di-fit sebelumnya
X_new_scaled = scaler.transform(X)

# Prediksi
prediksi = model.predict(X_new_scaled)
print(prediksi)

#Ambil baris ke-1055
data_prediksi2 = data_prediksi.iloc[[1054]]
data_prediksi2

# Pisahkan fitur (X) dan target (Y)
X2 = data_prediksi2.drop(columns='Attrition')
y2 = data_prediksi2['Attrition']

# Standardisasi dengan scaler yang telah di-fit sebelumnya
X_new_scaled2 = scaler.transform(X2)

# Prediksi
prediksi = model.predict(X_new_scaled2)
print(prediksi)

#Misal Pakai Data Baru Yang Belum Pernah Ada Di Data
data_prediksi3 = pd.read_csv('Prediksi3.csv')
data_prediksi3

# Pisahkan fitur (X) dan target (Y)
X3 = data_prediksi3.drop(columns='Attrition')
y3 = data_prediksi3['Attrition']

# Standardisasi dengan scaler yang telah di-fit sebelumnya
X_new_scaled3 = scaler.transform(X3)

# Prediksi
prediksi = model.predict(X_new_scaled3)
print(prediksi)